#!/usr/bin/env bash

set -e

# Configure PHP date.timezone
echo "date.timezone = $PHP_TIMEZONE" > /usr/local/etc/php/conf.d/timezone.ini

# Configure Apache Document Root
sed -i "s|DocumentRoot /var/www/html|DocumentRoot $APACHE_DOC_ROOT|" /etc/apache2/sites-available/000-default.conf
sed -i "s|DocumentRoot /var/www/html|DocumentRoot $APACHE_DOC_ROOT|" /etc/apache2/apache2.conf

# Configure XDebug remote host
if [ -z "$HOST_IP" ]; then
    # Allows to set HOST_IP by env variable because could be different from the one which come from ip route command
    HOST_IP=$(/sbin/ip route|awk '/default/ { print $3 }')
fi;
echo "xdebug.remote_host=$HOST_IP" > /usr/local/etc/php/conf.d/xdebug_remote_host.ini

exec "$@"
