#!/usr/bin/env bash

set -e

# Configure PHP date.timezone
echo "date.timezone = $PHP_TIMEZONE" > /usr/local/etc/php/conf.d/timezone.ini

# Configure Apache Document Root
mkdir -p $APACHE_DOC_ROOT
chown www-data:www-data $APACHE_DOC_ROOT
sed -i "s|DocumentRoot /var/www/html\$|DocumentRoot $APACHE_DOC_ROOT|" /etc/apache2/sites-available/000-default.conf
echo "<Directory $APACHE_DOC_ROOT>" > /etc/apache2/conf-available/document-root-directory.conf
echo "	AllowOverride All" >> /etc/apache2/conf-available/document-root-directory.conf
echo "	Require all granted" >> /etc/apache2/conf-available/document-root-directory.conf
echo "</Directory>" >> /etc/apache2/conf-available/document-root-directory.conf
a2enconf "document-root-directory.conf"

# Enable XDebug if needed
if [ "$XDEBUG_ENABLE" = "1" ]; then
    docker-php-ext-enable xdebug
    mv /usr/local/etc/php/conf.d/99-xdebug.ini.disabled /usr/local/etc/php/conf.d/99-xdebug.ini
    # Configure XDebug remote host
    if [ -z "$HOST_IP" ]; then
        # Allows to set HOST_IP by env variable because could be different from the one which come from ip route command
        HOST_IP=$(/sbin/ip route|awk '/default/ { print $3 }')
    fi;
    echo "xdebug.remote_host=$HOST_IP" > /usr/local/etc/php/conf.d/xdebug_remote_host.ini
fi;

# Configure sSMTP
if [ "$SSMTP_MAILHUB" ]; then
    echo "mailhub=$SSMTP_MAILHUB" >> /etc/ssmtp/ssmtp.conf
fi;
if [ "$SSMTP_AUTH_USER" ]; then
    echo "AuthUser=$SSMTP_AUTH_USER" >> /etc/ssmtp/ssmtp.conf
fi;
if [ "$SSMTP_AUTH_PASS" ]; then
    echo "AuthPass=$SSMTP_AUTH_PASS" >> /etc/ssmtp/ssmtp.conf
fi;

exec "apache2-foreground"
